// Code generated by MockGen. DO NOT EDIT.
// Source: tokens.go

// Package mock_tokens is a generated GoMock package.
package mock_tokens

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockTokener is a mock of Tokener interface
type MockTokener struct {
	ctrl     *gomock.Controller
	recorder *MockTokenerMockRecorder
}

// MockTokenerMockRecorder is the mock recorder for MockTokener
type MockTokenerMockRecorder struct {
	mock *MockTokener
}

// NewMockTokener creates a new mock instance
func NewMockTokener(ctrl *gomock.Controller) *MockTokener {
	mock := &MockTokener{ctrl: ctrl}
	mock.recorder = &MockTokenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTokener) EXPECT() *MockTokenerMockRecorder {
	return m.recorder
}

// GetDecimals mocks base method
func (m *MockTokener) GetDecimals(chain, symbol string) (int, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDecimals", chain, symbol)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetDecimals indicates an expected call of GetDecimals
func (mr *MockTokenerMockRecorder) GetDecimals(chain, symbol interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDecimals", reflect.TypeOf((*MockTokener)(nil).GetDecimals), chain, symbol)
}

// GetCurrency mocks base method
func (m *MockTokener) GetCurrency(chain, symbol string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrency", chain, symbol)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCurrency indicates an expected call of GetCurrency
func (mr *MockTokenerMockRecorder) GetCurrency(chain, symbol interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrency", reflect.TypeOf((*MockTokener)(nil).GetCurrency), chain, symbol)
}
